name: "GAE ENV Replace"
description: "Replace environment-variables in googles app engines test-app.yaml file"
author: "Heiko Schmidt"
branding:
  icon: "cloud"
  color: "orange"
runs:
  using: "docker"
  image: "Dockerfile"
