on: push
name: Test-Workflow
jobs:
  test:
    name: Test-Job
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 73h/gae-app-yaml-replace-env-variables@main
        env:
          VAR_ONE: "secret one"
          VAR_TWO: "secret two"
          ANOTHER_VAR: "another secret"
        with:
          app_yaml_path: "test-app.yaml"
